CREATE TABLE EMP (ENO INT,ENAME VARCHAR(50),JOB VARCHAR(50),SALARY int,COMMISSION int,DEPTNO int);
INSERT INTO EMP (ENO, ENAME, JOB, SALARY, COMMISSION, DEPTNO)
VALUES (1, 'John Doe', 'Manager', 5000, 1000, 10);

INSERT INTO EMP (ENO, ENAME, JOB, SALARY, COMMISSION, DEPTNO)
VALUES (2, 'Jane Smith', 'Analyst', 4000, NULL, 20);

INSERT INTO EMP (ENO, ENAME, JOB, SALARY, COMMISSION, DEPTNO)
VALUES (3, 'Mark Johnson', 'Clerk', 3000, NULL, 10);

INSERT INTO EMP (ENO, ENAME, JOB, SALARY, COMMISSION, DEPTNO)
VALUES (4, 'Michael Brown', 'Manager', 5500, 1500, 30);

INSERT INTO EMP (ENO, ENAME, JOB, SALARY, COMMISSION, DEPTNO)
VALUES (5, 'Sarah Williams', 'Analyst', 4200, NULL, 20);
