maths=[];
science=[];
english=[];
it=[];
for i in range(2):
    maths.append(int(input("enter the maths marks of student "+str(i+1)+" ")));
    science.append(int(input("enter the science marks of student "+str(i+1)+" ")));
    english.append(int(input("enter the english marks of student "+str(i+1)+" ")));
    it.append(int(input("enter the IT marks of student "+str(i+1)+" ")));
print("the highest in maths is "+str(max(maths)));
print("the highest in science is "+str(max(science)));
print("the highest in english is "+str(max(english)));
print("the highest in IT is "+str(max(it)));
print("-------------------------------------------");
print("the lowest in maths is "+str(min(maths)));
print("the lowest in science is "+str(min(science)));
print("the lowest in english is "+str(min(english)));
print("the lowest in IT is "+str(min(it)));
print("-------------------------------------------");
print("the average in maths is "+str(sum(maths)/len(maths)));
print("the average in science is "+str(sum(science)/len(science)));
print("the average in english is "+str(sum(english)/len(english)));
print("the average in IT is "+str(sum(it)/len(it)));
print("-------------------------------------------");
print("-------------------------------------------");
print("-------------------------------------------");
print("the highest in all subjects"+str(max([max(maths),max(science),max(english),max(it)])));
print("-------------------------------------------");
print("the lowest in all subjects"+str(min([min(maths),min(science),min(english),min(it)])));
print("-------------------------------------------");
print("the average of all subjects"+str(sum([sum(maths),sum(science),sum(english),sum(it)])/sum([len(maths),len(science),len(english),len(it)])));
